import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import webbrowser
from flask import Flask, jsonify, request
from flask_cors import CORS
from spotify import auth

app = Flask(__name__)
CORS(app)

auth_storage = {}

@app.route('/open_spotify', methods=['GET'])
def start_auth():
    auth_url = auth.get_auth_url()
    webbrowser.open(auth_url)

    return jsonify({"message": "Opened Spotify auth URL", "url": auth_url})


@app.route('/callback', methods=['GET'])
def callback():
    code = request.args.get('code')
    error = request.args.get('error')
    
    if error:
        return f"""
        <html>
            <body style="text-align: center; padding: 50px; font-family: Arial;">
                <h1>❌ Error</h1>
                <p>{error}</p>
                <p>You can close this tab.</p>
            </body>
        </html>
        """, 400
    
    if not code:
        return "<h1>No code received</h1>", 400
    
    # Exchange code for token using your functions
    token = auth.get_token_from_code(code)
    
    if token:
        # Store token temporarily
        auth_storage['token'] = token
        auth_storage['ready'] = True
        
        try:
            # Get currently playing
            print("\n--- Currently Playing ---")
            currently_playing = auth.get_currently_playing(token)
            
            if currently_playing and "item" in currently_playing:
                track = currently_playing["item"]
                print(f"Track: {track['name']}")
                print(f"Artist: {track['artists'][0]['name']}")
                print(f"ID: {track['id']}")
                
                # Use Gemini to analyze the track
                print("\n--- AI-Generated Audio Features (Gemini) ---")
                music_features = auth.analyze_track_with_gemini(track['name'], track['artists'][0]['name'])
                
                if music_features:
                    print("✓ Audio features generated by Gemini!")
                    print(f"Energy: {music_features['energy']}")
                    print(f"Danceability: {music_features['danceability']}")
                    print(f"Valence (happiness): {music_features['valence']}")
                    print(f"Tempo: {music_features['tempo']} BPM")
                    print(f"Acousticness: {music_features['acousticness']}")
                    print(f"Instrumentalness: {music_features['instrumentalness']}")
                else:
                    print("Could not generate audio features")
            else:
                print("No track currently playing")
            
            # Get queue
            print("\n--- Queue ---")
            queue = auth.get_current_queue(token)
            if queue and "queue" in queue:
                print(f"Number of tracks in queue: {len(queue['queue'])}")
                for i, track in enumerate(queue["queue"][:10], 1):  # Show first 10
                    print(f"{i}. {track['name']} - {track['artists'][0]['name']}")
            else:
                print("No queue data available")
                
        except Exception as e:
            print(f"\n❌ Error calling Spotify functions: {e}")
        
        return """
        <html>
            <body style="text-align: center; padding: 50px; font-family: Arial;">
                <h1>✅ Success!</h1>
                <p>Authentication complete. You can close this tab.</p>
            </body>
        </html>
        """
    else:
        return "<h1>Failed to get token</h1>", 400
    
@app.route('/get_track_info', methods=['GET'])
def get_track_info():
    """
    API endpoint to check if Spotify is authorized and get current track info.
    Frontend uses this to check if authorization is complete.
    """
    # Check if we have a token
    if 'token' not in auth_storage:
        return jsonify({"error": "Not authenticated"}), 401
    
    token = auth_storage['token']
    
    try:
        # Get currently playing track
        currently_playing = auth.get_currently_playing(token)
        
        if currently_playing and "item" in currently_playing:
            track = currently_playing["item"]
            
            # Get AI-generated audio features
            music_features = auth.analyze_track_with_gemini(
                track['name'], 
                track['artists'][0]['name']
            )
            
            # Return track info and features
            return jsonify({
                "authenticated": True,
                "track": {
                    "name": track['name'],
                    "artist": track['artists'][0]['name'],
                    "id": track['id'],
                    "album": track['album']['name'] if 'album' in track else None,
                    "image": track['album']['images'][0]['url'] if 'album' in track and track['album']['images'] else None
                },
                "features": music_features
            }), 200
        else:
            # No track playing, but still authenticated
            return jsonify({
                "authenticated": True,
                "track": None,
                "message": "No track currently playing"
            }), 200
            
    except Exception as e:
        print(f"Error in get_track_info: {e}")
        return jsonify({
            "error": str(e),
            "authenticated": False
        }), 500




if __name__ == '__main__':
    print("Starting Flask server on http://127.0.0.1:8888")
    app.run(host='127.0.0.1', port=8888, debug=True)